### ISSUE TITLE
No feature definition for critical-section

### ISSUE THREAD

**Issue by elfmimi** [ra-rs/ra#4]
To use take() ,
https://github.com/ra-rs/ra/blob/730714c2269de412a969778a8d68c4a009321d47/pac/ra4m1/src/lib.rs#L2204-L2214

`critical-section` feature needs to be added to the dependency. but it's not defined in Cargo.toml .
https://github.com/ra-rs/ra/blob/730714c2269de412a969778a8d68c4a009321d47/pac/ra4m1/Cargo.toml#L22-L23

**Comment by IsaacDynamo** [comment]
This branch seems to fix this issue.
https://github.com/9names/ra/tree/fix_critical_section

**Comment by AddisonH** [comment]
Fixed with commit 16bafa98f2ed5c4dfa3fb7cf973e58e7a471ef9f
